### PR TITLE
GHA: require codecov token explicitly

### PR DESCRIPTION
**Pull request by antisaling**
## Description
Attempt to fix the Python tests action (failing on #77).

## Merge criteria:

- [ ] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by tarilabs** [comment]
thank you @isinyaaa , it would look to me (based on separate tests from https://github.com/opendatahub-io/model-registry/pull/79) the only actual change required is to bump the codecov action version

i'm happy to merge this, just not sure about the "on workflow_call" as that to me looks like pertaining to workflow re-use (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_call) which isn't at play here 🤔 or am I missing something?

Let me know, then happy to merge it, many thanks again for investigating this!! 🙏

**Comment by antisaling** [comment]
> thank you @isinyaaa , it would look to me (based on separate tests from #79) the only actual change required is to bump the codecov action version
> 
> i'm happy to merge this, just not sure about the "on workflow_call" as that to me looks like pertaining to workflow re-use (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_call) which isn't at play here 🤔 or am I missing something?


I got the impression that it was necessary for dependabot PRs. I can drop this change then.

**Pull request merged**
