### PR TITLE
This commit explicitly puts model-registry resources into the opendat…

### PR DESCRIPTION
**Pull request by tonyxrmdavidson**
This commit explicitly puts model-registry resources into the opendatahub namespace.

### CODE REVIEW

**Review by tarilabs — COMMENTED** [review]
I understand this introduces an explicit namespace flag for all K8s api commands and the rest script.

/lgtm

I believe best if also @rkubis or @nehachopra27 can 👀  so to make sure it's consistent test-code-wise!

Thank you Tony

**Review by rkubis — APPROVED** [review]
Looks good :)

**Pull request merged**
